### ISSUE TITLE
Translation of Geolocation

### ISSUE THREAD

**Issue by JBPressac** [omeka/plugin-Geolocation#28]
Hello,
When the `<?php fire_plugin_hook('public_items_show', array('view' => $this, 'item' => $item)); ?>` is added to a show.php file, the map could be displayed on the public page of any item (see capture). However, is it possible to translate the title "Geolocation" (for instance by "Géolocalisation" in french) ? I could fill the translation of "geolocation" in one of the file of the [languages](https://github.com/omeka/plugin-Geolocation/tree/9a3a1fac99bb67566095fa52b4c609607825a0f3/languages) folder. But where is the file which generates the map ?
Thanks,

![documents envoyes par francois kerrien habitant a taule 29279 a l abbe jean-_2015-02-17_14-12-17](https://cloud.githubusercontent.com/assets/6371750/6228614/786950d2-b6ae-11e4-95e6-9afcbc6271d4.png)

**Comment by JBPressac** [comment]
Hello,
I found [some files to modify and implemented them in a fork of the plugin](https://github.com/JBPressac/plugin-Geolocation/commit/399a255b272fa059c902478063f63657a1c6caec). However, those modifications still not display the french translation of "Geolocation" on my web site. Do you have any idea why ?

What is more, I figured out that I should not manually modifiy the .po files but rather contribute to the translation of this plugin via Transifex, which I applied to.

Thanks,

**Comment by zerocrates** [comment]
The first of your changes, adding the translation call to the `h2`, is something that needs to get fixed in Geolocation. If you submit a pull request of just that change, I'll merge it.

You're right that it's best to update the actual translation through Transifex rather than directly in the file in the repository. When the code side is updated, we can push the updated source strings to Transifex so they can be updated there.
