### ISSUE TITLE
First impressions of Leaflet conversion

### ISSUE THREAD

**Issue by zerocrates** [omeka/plugin-Geolocation#49]
Branch "leaflet"

**Comment by mebrett** [comment]
Conflict with Exhibit Image Annotation may cause problems down the line.

Functionality is consistent enough with previous versions of Geolocation that I don't see the change being a huge issue for people. Adding locations to items and setting default zoom work as before.

The additional choices for map layer may overwhelm people, so the documentation may need to provide some guidance - does leaflet have documentation with images of all these layers? 

The "search by location" in advanced search doesn't seem to work all the time. A search for items within 10 miles of "London, England, United Kingdom" loads the previous search results, rather than a message that the address can't be parsed or that there are no items.

**Comment by zerocrates** [comment]
So, the layers aren't really a Leaflet thing.. they're agnostic as to the map provider, this is just a set of known freely-available tiles. I pared down to get to that list... we could pare down more if necessary. They're testable at http://leaflet-extras.github.io/leaflet-providers/preview/

The only real "new" functionality there is the Mapbox option, which will ask you to put in a Mapbox API key and give you access to their tiles.

**Comment by zerocrates** [comment]
You can try out the branch "compat" of ExhibitImageAnnotation, it should fix the incompatibility. You'd know better than me what to check to make sure EIA itself is still working fine... I did a very quick adding of an annotation and it seemed fine.

**Comment by mebrett** [comment]
compat works, so far as I can tell. No bugs in Geolocation or EIA.

**Comment by zerocrates** [comment]
There was definitely an issue in at least one theme I noticed on the public side, with the marker minimally and I think also with the map tiles themselves. It was down to the theme styling all `img`, I believe.

**Comment by mebrett** [comment]
Went through and looked at the items/map, exhibits with geolocation blocks, and items/show in all of the themes and only noticed a few things.

One is that the leaflet branch is doing that master *used* to do, and not re-centering when you click on an item in the Map Browse, so that you have to pan up in order to see the title of the item attached to the marker. 

The pagination buttons on items/map in Minimalist are out of alignment, but that's consistent on both master and leaflet.

For Thanks, Roy, on items/show, the geolocation display has a weird grid look and the marker is warped, regardless of the base map.

**Comment by zerocrates** [comment]
We're going to have to decide whether to "fix" thanks, roy or to provide more "protective" styles in Geolocation... that's unfortunate.

The recentering stuff... I think that's a tricky one but we'll see... there are some settings that can be changed, I think, but it might be basically the same as the old google maps: if the image hasn't loaded yet we don't know how tall it is and therefore don't know how much the map needs to move to fit the bubble in.

I've also noticed an occasional problem with recentering on the admin item form map tab... but it's inconsistent.

**Comment by zerocrates** [comment]
If you're using a Retina device you should see less-blurry rendering on latest pull with the Carto, Mapbox, and Stamen basemaps (as well as a nicer default map in the Carto section, Voyager)
