### ISSUE TITLE
Add support for latest Mapbox API

### ISSUE THREAD

**Issue by bmckinney** [omeka/plugin-Geolocation#50]
Enhancement request: support latest mapbox API.
 
## Mapbox Classic
The current classic URL template is: `https://api.tiles.mapbox.com/v4/mapbox.emerald/{z}/{x}/{y}.png?access_token=[your_access_key]` and supports the following style names:

- mapbox.streets
- mapbox.light
- mapbox.dark
- mapbox.satellite
- mapbox.streets-satellite
- mapbox.wheatpaste
- mapbox.streets-basic
- mapbox.comic
- mapbox.outdoors
- mapbox.run-bike-hike
- mapbox.pencil
- mapbox.pirates
- mapbox.emerald
- mapbox.high-contrast

## Current Mapbox 

The current mapbox URL template is: `https://api.mapbox.com/styles/v1/mapbox/streets-v10/tiles/256/{z}/{x}/{y}?access_token=[your_access_key]` and supports the following style names:

- streets-v10
- outdoors-v10
- light-v9
- dark-v9
- satellite-v9
- satellite-streets-v10
- navigation-preview-day-v4
- navigation-preview-night-v4
- navigation-guidance-day-v4
- navigation-guidance-night-v4

(see: https://www.mapbox.com/api-documentation/#styles)

**Comment by zerocrates** [comment]
We use https://github.com/leaflet-extras/leaflet-providers to run the selection of the various map layers, so the easiest pathway for us to add "new" Mapbox tile support would be to get it added to leaflet-providers...

I assume completely switching to the new style would be a no-go since it would break the currently-working styles, but perhaps there could be a separate "mapbox style" option.

**Comment by zerocrates** [comment]
This got done back in 2020 and was released in version 3.2.
